export const allProducts = [
  {
    id: "ANCHAL001",
    name: "ফ্রেশ ড্রাগন ফল",
    displayPrice: "৩৫০ টাকা",
    price: 350,
    prevPrice: 350,
    origin: "বান্দরবান ( লামা ) এর",
    details: "",
    category: "normal",
    image: "../assets/img/ii/product_1.webp",
    quantity: "১ কেজি",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন ফ্রেশ ড্রাগন ফল",
    preOrderPrice: "৩৫০ টাকা",
    preOrderQuantitiy: "১ কেজি",
    bestSeller: false,
    limit: 2,
    displayLimit: "২ কেজি",
    inStock: false,
  },
  {
    id: "ANCHAL002",
    name: "গাওয়া ঘি",
    displayPrice: "৫৪৫ টাকা",
    price: 545,
    prevPrice: 545,
    origin: "খামারগ্রাম ( সিরাজগঞ্জ ) এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " আমরা ঘরে বানানো কোনো ঘি নিয়ে কাজ করছিনা আপাতত, ঘি বরাবরই সিরাজগঞ্জেরটাই সেরা এবং খাঁটি । কারণ আপনি হয়তো জানেন ঘি চর অঞ্চলের গরুর দুধের থেকে বানালে তাতে আপনি আসল ঘিয়ের সুঘ্রাণ পাবেন । আমরা সিরাজগঞ্জের চর অঞ্চলের গরুর দুধ থেকে তৈরি ক্রীম নিয়ে এই ঘি বানানো হয় । মূলত বারবার এই ঘন দুধ জাল দেয়ার কারণে এই ঘি হয়ে ওঠে আরো বেশি খাঁটি ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " ঘি যেকোনো পাত্রে রাখা যায়, কিন্তু কাঁচের পাত্রে রাখা তুলনামূলকভাবে ভালো । সামনে আমরাও কাঁচের পাত্রে দেয়ার চেষ্টায় অব্যাহত থাকবো । মেয়াদউত্তীর্ণের তারিখ দেখে দয়া করে ঘি কিনবেন না, কারণ ঘি কখনোই নষ্ট হয়না বরং নষ্ট ঘি সংরক্ষণ করা হয়, এবং অনেকেই আছেন যারা ঔষধ হিসেবে এই ঘি ব্যাবহার করেন এবং তা দামেও বেশি থাকে । ঘি তিন মাস ধরে যেভাবে আছে সেভাবেই আপনি সংরক্ষণ করতে পারবেন, এরপর শুধু এর স্বাদ সামান্য বদলাবে ।",
    category: "normal",
    image: "../assets/img/ii/product_2.webp",
    quantity: "৪৩০ গ্রাম",
    preOrderable: false,
    bestSeller: true,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL003",
    name: "কালোজিরা ফুলের মধু",
    displayPrice: "৬৫০ টাকা",
    price: 650,
    prevPrice: 650,
    origin: "ঝিনাইদহ এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " মধু সাধারণত আপনারা অনেকেই অনেক ধরণের পরীক্ষার মাধ্যমে খাঁটি ব্যাপারটির খোঁজ নিয়ে থাকেন যা অনেক ক্ষেত্রেই মধু খাঁটি কিনা তা প্রমাণ করেনা । যেমন ইউটিউবে দেখা পিঁপড়া-পরীক্ষা, আগুন-পরীক্ষা ইত্যাদি আপনাকে কখনোই বুঝাতে পারবেনা মধু আসল কিনা । এজন্যই আমরা এক মধু গবেষকের সহায়তায় ঝিনাইদহ থেকে আনছি বিভিন্ন ফুলের মধু যা সম্পূর্ণভাবে ল্যাবে পরীক্ষিত । এছাড়াও আরো অনেক তথ্য আপনি অঞ্চলের ফেইসবুক গ্রুপে পাবেন ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " মধু সাধারণত ঠাণ্ডা জাগায় রাখাই উত্তম । অনেকেই মধু ফ্রিজে রাখেন যা মধুর স্বাদ নষ্ট করে দেয় । আপনি কক্ষ- তাপমাত্রায় এই মধু রাখবেন । কক্ষের তাপমাত্রা বেশি মনে হলে মধুর নিচে চ্যাপ্টা পাত্রে পানি ধেলে এর উপর মধুর পাত্র রেখে দিতে পারেন । ",
    category: "normal",
    image: "../assets/img/ii/product_3.webp",
    quantity: "৫০০ গ্রাম",
    preOrderable: false,
    bestSeller: false,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL004",
    name: "খামার ঘি",
    displayPrice: "৫৬০ টাকা",
    price: 560,
    prevPrice: 560,
    origin: "গোপালপুর এর",
    detailsTitle: "খামার ঘি কি?",
    details:
      " এটি গোপালপুরের স্পেশাল ঘি, যা দুধকে বেশি করে জাল দেয়ার মাধ্যমে তৈরি করা হয় । খামার ঘিয়ের রং একটু ঘন হবে গাওয়া ঘিয়ের তুলনায় ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " ঘি যেকোনো পাত্রে রাখা যায়, কিন্তু কাঁচের পাত্রে রাখা তুলনামূলকভাবে ভালো । সামনে আমরাও কাঁচের পাত্রে দেয়ার চেষ্টায় অব্যাহত থাকবো । মেয়াদউত্তীর্ণের তারিখ দেখে দয়া করে ঘি কিনবেন না, কারণ ঘি কখনোই নষ্ট হয়না বরং নষ্ট ঘি সংরক্ষণ করা হয়, এবং অনেকেই আছেন যারা ঔষধ হিসেবে এই ঘি ব্যাবহার করেন এবং তা দামেও বেশি থাকে । ঘি তিন মাস ধরে যেভাবে আছে সেভাবেই আপনি সংরক্ষণ করতে পারবেন, এরপর শুধু এর স্বাদ সামান্য বদলাবে ।",
    category: "normal",
    image: "../assets/img/ii/product_4.webp",
    quantity: "৪৩০ গ্রাম",
    preOrderable: false,
    bestSeller: false,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL005",
    name: "গরুর খাঁটি দুধ",
    displayPrice: "৮০ টাকা",
    price: 80,
    prevPrice: 80,
    origin: "বাঁশখালি এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " আমাদের গরুর দুধ সরাসরি বাঁশখালি থেকে ভোরে ভোরে এনে সংরক্ষণ করা হয় । এরপর আমরা দুপুরের মধ্যেই দুধের ডেলিভারি দিয়ে থাকি ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses: " অবশ্যই দুধের প্যাকেট পাওয়ার পর ফ্রিজে রাখুন ।",
    category: "normal",
    image: "../assets/img/ii/product_5.webp",
    quantity: "১ লিটার",
    preOrderable: false,
    bestSeller: false,
    limit: 3,
    displayLimit: "৩ লিটার",
    inStock: true,
  },
  {
    id: "ANCHAL006",
    name: "বুনো মধু",
    displayPrice: "৪৫০ টাকা",
    price: 450,
    prevPrice: 450,
    origin: "সুন্দরবন এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " মধু সাধারণত আপনারা অনেকেই অনেক ধরণের পরীক্ষার মাধ্যমে খাঁটি ব্যাপারটির খোঁজ নিয়ে থাকেন যা অনেক ক্ষেত্রেই মধু খাঁটি কিনা তা প্রমাণ করেনা । যেমন ইউটিউবে দেখা পিঁপড়া-পরীক্ষা, আগুন-পরীক্ষা ইত্যাদি আপনাকে কখনোই বুঝাতে পারবেনা মধু আসল কিনা । এজন্যই আমরা এক মধু গবেষকের সহায়তায় ঝিনাইদহ থেকে আনছি বিভিন্ন ফুলের মধু যা সম্পূর্ণভাবে ল্যাবে পরীক্ষিত । এছাড়াও আরো অনেক তথ্য আপনি অঞ্চলের ফেইসবুক গ্রুপে পাবেন ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " মধু সাধারণত ঠাণ্ডা জাগায় রাখাই উত্তম । অনেকেই মধু ফ্রিজে রাখেন যা মধুর স্বাদ নষ্ট করে দেয় । আপনি কক্ষ- তাপমাত্রায় এই মধু রাখবেন । কক্ষের তাপমাত্রা বেশি মনে হলে মধুর নিচে চ্যাপ্টা পাত্রে পানি ধেলে এর উপর মধুর পাত্র রেখে দিতে পারেন । ",
    category: "normal",
    image: "../assets/img/ii/product_6.webp",
    quantity: "৫০০ গ্রাম",
    preOrderable: false,
    bestSeller: true,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL007",
    name: "সরিষার তেল",
    displayPrice: "২১০ টাকা",
    price: 210,
    prevPrice: 210,
    origin: "গোপালপুর এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " আমাদের সরিষার তেল সম্পূর্ণভাবে গোপালপুরের সরিষার ক্ষেত থেকে সরিষা সংগ্রহ করে এবং তা মেশিনে ভাঙ্গিয়ে সংগ্রহ করা হয় ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " সরিষার তেল আপনি যেকোনো জাগায় সংরক্ষণ করতে পারেন তবে ঠাণ্ডা জাগায় রাখাই উত্তম । চুলা থেকে যতোটা সম্ভব দূরে রাখা উচিৎ কারণ চুলার উত্তাপে তেলের বোতল আঠালো হয়ে যায় প্রায়ই যা তেলের ক্ষতি না করলেও আপনার ব্যাবহার করতে কষ্ট হতে পারে ।",
    category: "normal",
    image: "../assets/img/ii/product_7.webp",
    quantity: "১ লিটার",
    preOrderable: false,
    bestSeller: false,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL008",
    name: "লিচু ফুলের মধু",
    displayPrice: "৩৬০ টাকা",
    price: 360,
    prevPrice: 360,
    origin: "ঝিনাইদহ এর",
    detailsTitle: "কেন খাঁটি?",
    details:
      " মধু সাধারণত আপনারা অনেকেই অনেক ধরণের পরীক্ষার মাধ্যমে খাঁটি ব্যাপারটির খোঁজ নিয়ে থাকেন যা অনেক ক্ষেত্রেই মধু খাঁটি কিনা তা প্রমাণ করেনা । যেমন ইউটিউবে দেখা পিঁপড়া-পরীক্ষা, আগুন-পরীক্ষা ইত্যাদি আপনাকে কখনোই বুঝাতে পারবেনা মধু আসল কিনা । এজন্যই আমরা এক মধু গবেষকের সহায়তায় ঝিনাইদহ থেকে আনছি বিভিন্ন ফুলের মধু যা সম্পূর্ণভাবে ল্যাবে পরীক্ষিত । এছাড়াও আরো অনেক তথ্য আপনি অঞ্চলের ফেইসবুক গ্রুপে পাবেন ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " মধু সাধারণত ঠাণ্ডা জাগায় রাখাই উত্তম । অনেকেই মধু ফ্রিজে রাখেন যা মধুর স্বাদ নষ্ট করে দেয় । আপনি কক্ষ- তাপমাত্রায় এই মধু রাখবেন । কক্ষের তাপমাত্রা বেশি মনে হলে মধুর নিচে চ্যাপ্টা পাত্রে পানি ধেলে এর উপর মধুর পাত্র রেখে দিতে পারেন । ",
    category: "normal",
    image: "../assets/img/ii/product_8.webp",
    quantity: "৫০০ গ্রাম",
    preOrderable: false,
    bestSeller: false,
    limit: 0,
    displayLimit: "",
    inStock: true,
  },
  {
    id: "ANCHAL009",
    name: "পোড়াবাড়ির চমচম",
    displayPrice: "৩২৫ টাকা",
    price: 325,
    prevPrice: 325,
    origin: "টাঙ্গাইল এর",
    detailsTitle: "কেন কিনবেন?",
    details:
      " আপনারা চমচম হয়তো নিজস্ব এলাকা থেকে অনেকেই কিনে খান । সেক্ষেত্রে আপনারা ফ্রেশ ও স্বাস্থ্যকর চমচম খেতে চান । আমরা টাঙ্গাইলের ঐতিহ্যবাহী পোড়াবাড়ীর চমচম সরাসরি টাঙ্গাইল সদর থেকে আনছি প্রি- অর্ডারের মাধ্যমে যাতে আপনারা ফ্রেশ ও সুস্বাদু চমচম উপভোগ করতে পারেন । আমরা প্রি - অর্ডার সপ্তাহের শেষের পরদিনই চমচম হাতে পাই এবং ঐদিনই পৌঁছে দেই ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " চমচমের প্যাকেট পাওয়ার পর নরমাল ফ্রিজে রাখুন অথবা এমনি রাখলেও ২-৩ দিন চমচম ভালো থাকবে ",
    category: "normal",
    image: "../assets/img/ii/product_9.webp",
    quantity: "১ কেজি",
    preOrderable: true,
    preOrderTitle: "প্রি – অর্ডার করুন পোড়াবাড়ির চমচম",
    preOrderPrice: "৩২৫ টাকা",
    preOrderQuantitiy: "১ কেজি",
    bestSeller: true,
    limit: 1,
    displayLimit: "১ কেজি",
    inStock: true,
  },
  {
    id: "ANCHAL020",
    name: "ঝড়াটিয়ার দই",
    displayPrice: "৩৮০ টাকা",
    price: 380,
    prevPrice: 380,
    origin: "টাঙ্গাইল এর",
    detailsTitle: "কেন কিনবেন?",
    details:
      " আপনারা দই হয়তো নিজস্ব এলাকা থেকে অনেকেই কিনে খান । সেক্ষেত্রে আপনারা ফ্রেশ ও স্বাস্থ্যকর দই খেতে চান । আমরা টাঙ্গাইলের ঐতিহ্যবাহী ঝড়াটিয়ার দই সরাসরি টাঙ্গাইল সদর থেকে আনছি প্রি- অর্ডারের মাধ্যমে যাতে আপনারা ফ্রেশ ও সুস্বাদু দই উপভোগ করতে পারেন । আমরা প্রি - অর্ডার সপ্তাহের শেষের পরদিনই দই হাতে পাই এবং ঐদিনই পৌঁছে দেই ।",
    detailsUsesTitle: "সংরক্ষণ ",
    detailsUses:
      " দই এর হাড়ি পাওয়ার পর নরমাল ফ্রিজে রাখুন অথবা এমনি রাখলেও ২-৩ দিন দই ভালো থাকবে ",
    category: "normal",
    image: "../assets/img/ii/product_10.webp",
    quantity: "১ কেজি",
    preOrderable: true,
    preOrderTitle: "প্রি – অর্ডার করুন ঝড়াটিয়ার দই",
    preOrderPrice: "৩৮০ টাকা",
    preOrderQuantitiy: "১ কেজি",
    bestSeller: false,
    limit: 1,
    displayLimit: "১ কেজি",
    inStock: true,
  },
  {
    id: "ANCHAL010",
    name: "চালের রুটি",
    displayPrice: "৮ টাকা",
    price: 8,
    prevPrice: 8,
    origin: "ঘরের তৈরি ফ্রোজেন",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-1.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন চালের রুটি",
    preOrderPrice: "৮ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL011",
    name: "ফ্রোজেন পরোটা",
    displayPrice: "১০ টাকা",
    price: 10,
    prevPrice: 10,
    origin: "ঘরের তৈরি",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-2.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন পরোটা",
    preOrderPrice: "১০ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL012",
    name: "ফ্রোজেন রুটি",
    displayPrice: "৭ টাকা",
    price: 7,
    prevPrice: 7,
    origin: "ঘরের তৈরি",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-3.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন রুটি",
    preOrderPrice: "৭ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL013",
    name: "ফ্রোজেন অন্থন",
    displayPrice: "১০ টাকা",
    price: 10,
    prevPrice: 10,
    origin: "ঘরের তৈরি",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-8.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন অন্থন",
    preOrderPrice: "১০ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL014",
    name: "আমের আচার",
    displayPrice: "১৮০ টাকা",
    price: 180,
    prevPrice: 180,
    origin: "ঘরের তৈরি",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-5.webp",
    quantity: "৫০০ গ্রাম",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন আমের আচার",
    preOrderPrice: "১৮০ টাকা",
    preOrderQuantitiy: "১ ৫০০ গ্রাম",
    bestSeller: false,
    limit: 0,
    displayLimit: "৫০০ গ্রাম",
    inStock: true,
  },
  {
    id: "ANCHAL015",
    name: "নারকেল পুলি",
    displayPrice: "৮ টাকা",
    price: 8,
    prevPrice: 8,
    origin: "তেলে ভাজা",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-9.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন নারকেল পুলি",
    preOrderPrice: "৮ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL016",
    name: "হাত ঝাড়া পিঠা",
    displayPrice: "১০ টাকা",
    price: 10,
    prevPrice: 10,
    origin: "ঘরের তৈরি",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-4.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন হাত ঝাড়া পিঠা",
    preOrderPrice: "১০ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL017",
    name: "চিকেন সমুচা",
    displayPrice: "১০ টাকা",
    price: 10,
    prevPrice: 10,
    origin: "ঘরের তৈরি ফ্রোজেন",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-7.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন চিকেন সমুচা",
    preOrderPrice: "১০ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL018",
    name: "নারকেল পুলি",
    displayPrice: "১০ টাকা",
    price: 10,
    prevPrice: 10,
    origin: "ঘরের তৈরি ফ্রোজেন",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-6.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন পাটিসাপটা",
    preOrderPrice: "১০ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
  {
    id: "ANCHAL019",
    name: "চিকেন রোল",
    displayPrice: "১২ টাকা",
    price: 12,
    prevPrice: 12,
    origin: "ঘরের তৈরি ফ্রোজেন",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eligendi laborum ab in libero explicabo necessitatibus vel aliquid doloribus quia enim, sapiente repellat, provident debitis error sint minima nesciunt pariatur.",
    category: "home-made",
    image: "../assets/img/ii/home-made-10.webp",
    quantity: "১ পিস",
    preOrderable: false,
    preOrderTitle: "প্রি – অর্ডার করুন চিকেন রোল",
    preOrderPrice: "১২ টাকা",
    preOrderQuantitiy: "১ পিস",
    bestSeller: false,
    limit: 30,
    displayLimit: "৩০ পিস",
    inStock: true,
  },
];
